services:
  vodum:
    image: nexius2/vodum:latest
    container_name: vodum
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8097:5000"

    volumes:
      - ./appdata:/appdata
      - ./logs:/appdata/logs
      - ./backups:/appdata/backups

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/ >/dev/null || exit 1"]
      interval: 240s
      timeout: 8s
      retries: 5
      start_period: 30s